<?php
/**
 * AssetsDetail
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hackathon Web API
 *
 * Hackathonの Web API 仕様書
 *
 * OpenAPI spec version: 0.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * AssetsDetail Class Doc Comment
 *
 * @category    Class */
 // @description アセット作成情報
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AssetsDetail implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'AssetsDetail';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'assets_name' => 'string',
        'description' => 'string',
        'floating_point' => 'int',
        'initial_supply' => 'int'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'assets_name' => 'assetsName',
        'description' => 'description',
        'floating_point' => 'floatingPoint',
        'initial_supply' => 'initialSupply'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'assets_name' => 'setAssetsName',
        'description' => 'setDescription',
        'floating_point' => 'setFloatingPoint',
        'initial_supply' => 'setInitialSupply'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'assets_name' => 'getAssetsName',
        'description' => 'getDescription',
        'floating_point' => 'getFloatingPoint',
        'initial_supply' => 'getInitialSupply'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['assets_name'] = isset($data['assets_name']) ? $data['assets_name'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['floating_point'] = isset($data['floating_point']) ? $data['floating_point'] : null;
        $this->container['initial_supply'] = isset($data['initial_supply']) ? $data['initial_supply'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['assets_name'] === null) {
            $invalid_properties[] = "'assets_name' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalid_properties[] = "'description' can't be null";
        }
        if ($this->container['floating_point'] === null) {
            $invalid_properties[] = "'floating_point' can't be null";
        }
        if ($this->container['initial_supply'] === null) {
            $invalid_properties[] = "'initial_supply' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['assets_name'] === null) {
            return false;
        }
        if ($this->container['description'] === null) {
            return false;
        }
        if ($this->container['floating_point'] === null) {
            return false;
        }
        if ($this->container['initial_supply'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets assets_name
     * @return string
     */
    public function getAssetsName()
    {
        return $this->container['assets_name'];
    }

    /**
     * Sets assets_name
     * @param string $assets_name アセット名
     * @return $this
     */
    public function setAssetsName($assets_name)
    {
        $this->container['assets_name'] = $assets_name;

        return $this;
    }

    /**
     * Gets description
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     * @param string $description 説明
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets floating_point
     * @return int
     */
    public function getFloatingPoint()
    {
        return $this->container['floating_point'];
    }

    /**
     * Sets floating_point
     * @param int $floating_point 浮動小数点
     * @return $this
     */
    public function setFloatingPoint($floating_point)
    {
        $this->container['floating_point'] = $floating_point;

        return $this;
    }

    /**
     * Gets initial_supply
     * @return int
     */
    public function getInitialSupply()
    {
        return $this->container['initial_supply'];
    }

    /**
     * Sets initial_supply
     * @param int $initial_supply 数量
     * @return $this
     */
    public function setInitialSupply($initial_supply)
    {
        $this->container['initial_supply'] = $initial_supply;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


