<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hackathon Web API
 *
 * Hackathonの Web API 仕様書
 *
 * OpenAPI spec version: 0.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addObjectValueUsingPOST
     *
     * オブジェクトの登録.
     *
     */
    public function testAddObjectValueUsingPOST()
    {

    }

    /**
     * Test case for createAssetsUsingPOST
     *
     * アセット作成.
     *
     */
    public function testCreateAssetsUsingPOST()
    {

    }

    /**
     * Test case for createNewAccountUsingPOST
     *
     * ユーザーの作成.
     *
     */
    public function testCreateNewAccountUsingPOST()
    {

    }

    /**
     * Test case for createObjectUsingPOST
     *
     * オブジェクトの作成.
     *
     */
    public function testCreateObjectUsingPOST()
    {

    }

    /**
     * Test case for findAssetsUsingGET
     *
     * アセット検索.
     *
     */
    public function testFindAssetsUsingGET()
    {

    }

    /**
     * Test case for findCountObjectValuesUsingGET
     *
     * オブジェクトの登録データの検索結果件数.
     *
     */
    public function testFindCountObjectValuesUsingGET()
    {

    }

    /**
     * Test case for findObjectValuesUsingGET
     *
     * オブジェクトの登録データの検索.
     *
     */
    public function testFindObjectValuesUsingGET()
    {

    }

    /**
     * Test case for getObjectCountUsingGET
     *
     * オブジェクトの登録件数の参照.
     *
     */
    public function testGetObjectCountUsingGET()
    {

    }

    /**
     * Test case for getObjectValueUsingGET
     *
     * オブジェクトの参照.
     *
     */
    public function testGetObjectValueUsingGET()
    {

    }

    /**
     * Test case for getObjectValuesUsingGET
     *
     * オブジェクトの登録データの参照.
     *
     */
    public function testGetObjectValuesUsingGET()
    {

    }

    /**
     * Test case for queryAssetsBalanceUsingGET
     *
     * アセットの残高照会.
     *
     */
    public function testQueryAssetsBalanceUsingGET()
    {

    }

    /**
     * Test case for queryAssetsTradingHistoryUsingGET
     *
     * アセットの取引履歴参照.
     *
     */
    public function testQueryAssetsTradingHistoryUsingGET()
    {

    }

    /**
     * Test case for sendAssetsUsingPOST
     *
     * アセットの送信.
     *
     */
    public function testSendAssetsUsingPOST()
    {

    }

}
